name: FoodApp
description: A simple food devliver app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen:
  sqflite: ^1.1.6
  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  url_launcher: ^5.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  carousel_slider: ^1.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/diamond.png
    - assets/images/a.jpg
    - assets/images/b.jpg
    - assets/images/c.jpeg
    - assets/images/d.jpg
    - assets/images/e.jpeg
    - assets/images/f.jpeg
    - assets/images/foods/a.jpeg
    - assets/images/foods/b.jpeg
    - assets/images/foods/c.jpg
    - assets/images/foods/d.jpeg
    - assets/images/foods/p.jpeg

    - assets/images/categories/camera.png
    - assets/images/categories/church.png
    - assets/images/categories/football.png
    - assets/images/categories/groceries.png
    - assets/images/categories/mosque.png
    - assets/images/categories/puzzle.png
    - assets/images/categories/radio.png
    - assets/images/categories/travel.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #